site_name: Dexter
repo_url:  https://github.com/conery/dexter
copyright: Copyright &copy 2025 John Conery

theme:
  name: "readthedocs"

extra:
  version: Version 0.0.5

extra_css:
  - css/dex.css

markdown_extensions:
  - admonition

plugins:
  - search
  - callouts
  - mkdocstrings
  - codeinclude:
      title_mode: none

nav:
  - "Introduction": 
    - "Overview": index.md
    - "History": history.md
    - "Double Entry Bookkeeping": deb.md
    - "Envelope Budgeting":  envelopes.md
    - "Philosophy": philosophy.md
    - "Workflow": workflow.md
  - "Installation":
    - "Dexter": dex_install.md
    - "Database Server": db_server.md
  - "Tutorial":
    - "Example Data": folder.md
    - "Shell Command": dex.md
    - "Defining Accounts": accounts.md
    - "Initialize the Database": tut_init.md
    - "Import Regular Expressions": tut_regexp.md
    - "Import CSV Files": dex_import.md
    - "Pair Transactions": dex_pair.md
    - "Review Unpaired Transactions": dex_review.md
    - "Add New Transaction": dex_add.md
    - "Select Transactions": dex_select.md
    - "Reports": dex_report.md
    - "Back Up the Database": dex_save_restore.md
  - "User Documentation":
    - "Configuration": config.md
    - "Command Line Options": options.md
    - "Regular Expressions": regexp.md
    - "dex import": dex_import.md
    - "dex init": dex_init.md
  - "The Budget Model":
    - "Envelope Budgeting with Dexter": envelopes_dex.md
    - "Account Balances": balances.md
    - "Budget Transactions": budget_trans.md
    - "Expense Account Balances": balance_expenses.md
    - "Income Account Balances": balance_income.md
    - "Adjustments": adjustments.md
    - "Using the Equity Account": equity.md
    - "Nominal Accounts": nominal.md
    - "Recap": recap.md
  - "Dexter and hledger": 
    - "Notes for hledger Users": hledger.md
  - "API":
    - "Database API": api.md
  - "Reference":
    - "Modules": modules.md


