site_name: Dexter

theme:
  name: "readthedocs"

extra:
  version: Version 0.0.5

extra_css:
  - css/dex.css

markdown_extensions:
  - admonition

plugins:
  - search
  - callouts
  - mkdocstrings
  - codeinclude:
      title_mode: none

nav:
  - "Introduction": 
    - "Overview": index.md
    - "History": history.md
    - "Double Entry Bookkeeping": deb.md
    - "Envelope Budgeting":  envelopes.md
    - "Philosophy": philosophy.md
    - "Workflow": workflow.md
  - "Running the Scripts":
    - "Shell Command": dex.md
  - "The Budget Model":
    - "Envelope Budgeting with Dexter": dexenvelopes.md
    - "Account Balances": balances.md
    - "Budget Transactions": budgettrans.md
    - "Expense Account Balances": expbal.md
    - "Income Account Balances": incbal.md
    - "Adjustments": adjustments.md
    - "Using the Equity Account": equity.md
    - "Nominal Accounts": nominal.md
    - "Recap": recap.md
  - "API":
    - "Database API": api.md
  - "Reference":
    - "Modules": modules.md


