site_name: Dexter

theme:
  name: "readthedocs"

extra:
  version: Version 0.0.5

extra_css:
  - css/dex.css

markdown_extensions:
  - admonition

plugins:
  - search
  - callouts
  - mkdocstrings
  - codeinclude:
      title_mode: none

nav:
  - "Home":
    - "Introduction": 
      - "Overview": index.md
      - "History": history.md
      - "Double Entry Bookkeeping": deb.md
      - "Philosophy": philosophy.md
      - "Workflow": workflow.md
    - "The Budget Model": budgets.md
  - "Running the Applications":
    - "dex Command Line": dex.md
  - "API":
    - "Database API": api.md
  - "Reference":
    - "Source Directory": tbd.md
    - "Modules": tbd.md


